package ch.m335.fallcounter.activity;

import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.content.Context;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.os.Bundle;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.TextView;

import java.util.Calendar;

import ch.m335.fallcounter.R;
import ch.m335.fallcounter.services.CalculatorService;
import ch.m335.fallcounter.services.DataHandler;

public class MainActivity extends AppCompatActivity {
    EditText editTextDate1;
    EditText editTextDate2;
    Calendar calendar = Calendar.getInstance();

    private SensorManager sensorManager;
    private Sensor accelerometer;
    private SensorEventListener sensorEventListener;
    float x, y, z;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        DataHandler dataHandler = new DataHandler(getSharedPreferences("FallCounter", Context.MODE_PRIVATE));

        editTextDate1 = findViewById(R.id.startDate);
        editTextDate2 = findViewById(R.id.endDate);

        editTextDate1.setOnClickListener(v -> showDatePickerDialog(editTextDate1));
        editTextDate2.setOnClickListener(v -> showDatePickerDialog(editTextDate2));




        //sensor
        sensorManager = (SensorManager) getSystemService(Context.SENSOR_SERVICE);
        accelerometer = sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);


        sensorEventListener = new SensorEventListener() {
            @Override
            public void onSensorChanged (SensorEvent event){
                // generated by ChatGPT
                // detect falling
                float threshold = 6f;
                x = event.values[0];
                y = event.values[1];
                z = event.values[2];

                // acceleration
                double magnitude = Math.sqrt(x * x + y * y + z * z);

                if (magnitude < threshold) {
                    //falling
                    new CalculatorService().incrementCounter();
                }

            }

            @Override
            public void onAccuracyChanged(Sensor sensor, int i) {}
        };

        sensorManager.registerListener(sensorEventListener, accelerometer, SensorManager.SENSOR_DELAY_NORMAL);
    }

    private void showDatePickerDialog(EditText editTextDate) {
        DatePickerDialog datePickerDialog = new DatePickerDialog(
                this,
                new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(DatePicker view, int year, int monthOfYear, int dayOfMonth) {
                        editTextDate.setText(dayOfMonth + "/" + (monthOfYear + 1) + "/" + year);
                    }
                },
                calendar.get(Calendar.YEAR),
                calendar.get(Calendar.MONTH),
                calendar.get(Calendar.DAY_OF_MONTH)
        );

        datePickerDialog.show();
    }

//https://stackoverflow.com/questions/4848490/android-how-to-approach-fall-detection-algorithm/44848490#44848490
}