package ch.m335.fallcounter.activity;

import androidx.appcompat.app.AppCompatActivity;

import android.app.DatePickerDialog;
import android.content.Context;
import android.content.SharedPreferences;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.os.Bundle;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.TextView;

import java.time.LocalDate;
import java.util.Calendar;

import ch.m335.fallcounter.R;
import ch.m335.fallcounter.services.CalculatorService;
import ch.m335.fallcounter.services.DataHandler;

public class MainActivity extends AppCompatActivity {
    TextView messageTextView;
    EditText editTextDate1;
    EditText editTextDate2;
    Calendar calendar = Calendar.getInstance();

    private SensorManager sensorManager;
    private Sensor accelerometer;
    private SensorEventListener sensorEventListener;
    float x, y, z;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        LocalDate today = LocalDate.now();

        //set shared Preferences start
        SharedPreferences sharedPreferences = getSharedPreferences("FallCounter", Context.MODE_PRIVATE);
        if(sharedPreferences==null){
            SharedPreferences preferences = getSharedPreferences("FallCounter", Context.MODE_PRIVATE);
            SharedPreferences.Editor editor = preferences.edit();
            editor.apply();
        }
        DataHandler.setSharedPreference(sharedPreferences);
        //set shared Preferences end

        CalculatorService calculatorService = new CalculatorService();

        //set message number start
        int sum = calculatorService.getSum(today,today);
        messageTextView = findViewById(R.id.messageTextView);

        String newText = messageTextView.getText().toString().replace("_", String.valueOf(sum));
        messageTextView.setText(newText);
        // set message number end

        //date textfields start
        editTextDate1 = findViewById(R.id.startDate);
        editTextDate2 = findViewById(R.id.endDate);

        editTextDate1.setOnClickListener(v -> showDatePickerDialog(editTextDate1));
        editTextDate2.setOnClickListener(v -> showDatePickerDialog(editTextDate2));

        editTextDate1.setText(today.toString());
        editTextDate2.setText(today.toString());
        //date textfields end

        //sensor config start
        sensorManager = (SensorManager) getSystemService(Context.SENSOR_SERVICE);
        accelerometer = sensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);

        sensorEventListener = new SensorEventListener() {
            @Override
            public void onSensorChanged (SensorEvent event){
                if (detectFalling(event)) {
                    calculatorService .incrementCounter();
                }
            }

            @Override
            public void onAccuracyChanged(Sensor sensor, int i) {}
        };

        sensorManager.registerListener(sensorEventListener, accelerometer, SensorManager.SENSOR_DELAY_NORMAL);
        //sensor config end
    }

    private void showDatePickerDialog(EditText editTextDate) {
        DatePickerDialog datePickerDialog = new DatePickerDialog(
                this,
                new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(DatePicker view, int year, int month, int day) {
                        editTextDate.setText(day + "-" + (month + 1) + "-" + year);
                    }
                },
                calendar.get(Calendar.YEAR),
                calendar.get(Calendar.MONTH),
                calendar.get(Calendar.DAY_OF_MONTH)
        );

        datePickerDialog.show();
    }

    private boolean detectFalling(SensorEvent event){
        // generated by ChatGPT
        float threshold = 6f;
        x = event.values[0];
        y = event.values[1];
        z = event.values[2];

        // acceleration
        double magnitude = Math.sqrt(x * x + y * y + z * z);

        return magnitude < threshold;
    }

}